config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'repos#index'

  resources :repos, except: %i[edit update]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
# frozen_string_literal: true

class Commit < ApplicationRecord
  validates :sha,          presence: true, format: /\A[a-f0-9]{40}\z/
  validates :message,      presence: true
  validates :commited_at,  presence: true
  validates :author_name,  presence: true
  validates :author_email, presence: true

  belongs_to :repo

  def message_subject
    message.split("\n").first
  end

  def message_body
    message.split("\n").drop(1).join("\n")
  end

  def url
    "https://github.com/#{repo.owner}/#{repo.name}/commit/#{sha}"
  end
end

app/models/repo.rb
# frozen_string_literal: true

class Repo < ApplicationRecord
  validates :owner, presence: true
  validates :name,  presence: true
  validates :name, uniqueness: { scope: :owner }

  enum update_status: %i[update_in_progress update_finished update_errored]

  has_many :commits, dependent: :destroy

  def url
    "https://github.com/#{owner}/#{name}"
  end

  def issues_url
    url + '/issues'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/repos_controller.rb
# frozen_string_literal: true

class ReposController < ApplicationController
  before_action :set_repo, only: %i[show destroy]

  def index
    redirect_to(new_repo_path) && return unless Repo.exists?
    redirect_to Repo.first
  end

  def show
    @repos = Repo.all
  end

  def new
    @repo = Repo.new
  end

  def create
    @repo = Repo.new(repo_params)

    if @repo.save
      UpdateRepoDataJob.perform_later(@repo)
      redirect_to @repo
    else
      render :new
    end
  end

  def destroy
    @repo.destroy
    redirect_to repos_url
  end

  private

  def set_repo
    @repo = Repo.find(params[:id])
  end

  def repo_params
    params.require(:repo).permit(:owner, :name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/repos_helper.rb
# frozen_string_literal: true

module ReposHelper
  def repo_nav_item_classes(repo)
    classes = %w[nav-link]
    classes << 'active' if repo == @repo
    classes.join(' ')
  end
end

app/views/commits/_commit.html.erb
<div class="list-group-item">
  <div class="d-flex w-100 justify-content-between">
    <%= link_to commit.url do %>
      <h5 class="mb-1" title="<%= commit.message_subject %>">
        <%= commit.message_subject.truncate(90) %>
      </h5>
    <% end %>
  </div>

  <div class="w-100">
    <pre><%= commit.message_body %></pre>
  </div>

  <small class="text-muted">
    <span title="<%= commit.commited_at.strftime('%Y-%m-%d %H:%M:%S') %>">
      <%= time_ago_in_words(commit.commited_at) %> ago
    </span>
    by
    <%= image_tag commit.author_avatar_url, width: 16, height: 16 %>
    <%= mail_to commit.author_email, commit.author_name %>
  </small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Repofeed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-4 mb-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/repos/_form.html.erb
<%= form_with(model: repo, local: true, class: 'form-inline') do |form| %>
    <% if repo.errors %>
        <div class="mb-2 w-100">
          <%= repo.errors.full_messages.join(', ') %>
        </div>
    <% end %>
  <div class="form-check mr-sm-2">
    <div class="field <%= 'has-danger' if repo.errors[:owner].present? %>">
      <%= form.text_field :owner, placeholder: 'owner (ex. rails)', class: 'form-control form-control-danger' %>
    </div>

    <div class="ml-sm-2 mr-sm-2">/</div>

    <div class="field mr-sm-2 mb-2 mb-sm-0 <%= 'has-danger' if repo.errors[:name].present? %>">
      <%= form.text_field :name, placeholder: 'name (ex. sprockets)', class: 'form-control form-control-danger' %>
    </div>

    <div class="field">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/repos/_info.html.erb
<div class="card mb-2">
  <div class="card-block">
    <h5>
      <%= image_tag @repo.owner_avatar_url, width: 32, heigth: 32 %>
      <%= link_to @repo.url do %>
        <%= @repo.owner %> / <%= @repo.name %>
      <% end %>
    </h5>
    <small>Stars: <%= @repo.stars_count %></small> |
    <small>Open Issues: <%= link_to @repo.open_issues_count, @repo.issues_url %></small> |

    <small><%= link_to 'Remove', @repo, method: :delete , class: 'pull-right text-danger' %></small>

  </div>
</div>

app/views/repos/_list.html.erb
<ul class="nav nav-pills flex-column">
  <% @repos.each do |repo| %>
    <li class="nav-item">
      <%= link_to "#{repo.owner}/#{repo.name}", repo, class: repo_nav_item_classes(repo) %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to '+ Add', new_repo_path, class: 'nav-link' %>
  </li>
</ul>

app/views/repos/_repo.html.erb
<div class="list-group">
  <%= render @repo.commits %>
</div>

app/views/repos/new.html.erb
<%= render 'form', repo: @repo %>

<% if Repo.exists? %>
  <%= link_to 'Back', repos_path, class: 'btn btn-secondary mt-2' %>
<% end %>

app/views/repos/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-3">
    <%= render 'list' %>
  </div>

  <div class="col-xs-12 col-md-9">
    <% if @repo.update_in_progress? %>
      <p data-repo-update-in-progress>Your repository data is now updated. Please wait...</p>
    <% elsif @repo.update_errored? %>
      <p>
        There was a problem updating this repo.
        Please check if it exists and GitHub is not down.
        You can <%= link_to 'remove it', @repo, method: :delete %>.
      </p>
    <% else %>
      <%= render 'info' %>
      <%= render @repo %>
    <% end %>
  </div>
</div>